# Generated by Django 3.0 on 2019-12-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title_minutes',
            new_name='time_minutes',
        ),
    ]
